#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=CLIPVP-CIFAR10
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:40:00
#SBATCH --mem=32000M
#SBATCH --output=outs/clipvp10_cross_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

# activate the environment
source activate dl2022

# Run 1: Visual prompting CLIP on CIFAR-10 with standard text prompt
code_dir=./

# Standard constants
arch="ViT-B/32"
text_prompt_template="This is a photo of a {}"
epochs=20

## Set of experiments on CIFAR-10
root=/scratch/$USER
mkdir -p $root

checkpoints=(./checkpoints/padding_30_cifar10_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1/model_best.pth.tar \
            ./checkpoints/padding_30_cifar100_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1/model_best.pth.tar \
            ./checkpoints/fixed_patch_1_cifar10_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1/model_best.pth.tar\
            ./checkpoints/fixed_patch_1_cifar100_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1/model_best.pth.tar\
            ./checkpoints/random_patch_1_cifar10_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1/model_best.pth.tar\
            ./checkpoints/random_patch_1_cifar100_clip_ViT-B/32_sgd_lr_40_decay_0_bsz_128_warmup_1000_trial_1/model_best.pth.tar)

methods=(padding padding fixed_patch fixed_patch random_patch random_patch)
prompt_sizes=(30 30 1 1 1 1)
model_dir="$HOME/uvadlc_practicals_2022/assignment2/part2/checkpoints"
image_dir="$HOME/uvadlc_practicals_2022/assignment2/part2/images"

for i in "${!checkpoints[@]}"; do
	method=${methods[$i]}
	prompt_size=${prompt_sizes[$i]}
    resume=${checkpoints[$i]}
	echo "Running experiment with $method and prompt size $prompt_size"
	python $code_dir/cross_dataset.py \
	    --arch $arch \
	    --text_prompt_template "$text_prompt_template" \
	    --epochs $epochs \
	    --root $root \
        --method $method \
	    --prompt_size $prompt_size \
	    --num_workers 3 \
	    --print_freq 100 \
		--evaluate\
        --resume $resume
    
done